version: '3.1'

services:

  web:
    build: .
    volumes:
     - .:/app
    ports:
     - "8000:8000"
    depends_on:
     - db

  db:
    image: mongo
    restart: always
    container_name: mongodb-fastapi-user-image
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: zackblack
      MONGO_INITDB_ROOT_PASSWORD: alohomora1234
    volumes:
      - ./data:/data/db